---
title: "Everest Bio"
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
# output: 
#   flexdashboard::flex_dashboard:
#     #storyboard: true
#     orientation: rows
#     logo: https://raw.githubusercontent.com/fabbiocrux/Figures/main/Everest-bio/logos/favicon-tool.png
#     #vertical_layout: scroll
#     social: menu
#date: "Version of the Document:  `r format(Sys.time(), '%d %B, %Y')`" 
#author: "Université de Lorraine"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  include=TRUE, warning = FALSE, message = FALSE)
#source()
library(leaflet)
library(tidyverse)
library(shiny)
library(shinyWidgets)

# Link for the Figures
URL = c('https://raw.githubusercontent.com/fabbiocrux/Figures/main/')

```

## Presentation

### Goal of Everest Bio : 

> To develop a generic methodology to assess the **ecosystem services** rendered by industrial activities operating in short circuit in order to improve decision-making by industrial and public actors. 


<a href = "https://erpi.univ-lorraine.fr/">Made by Université de Lorraine</a>

## Consentement



## Describing

### Who you are?


```{r}

fluidPage(
 prettyRadioButtons(
   inputId = "radio1",
   label = "Votre profile est plutôt:",
   choices = c("Agent Territoirial", "Agent d'Entreprise", "Other"),
    icon = icon("thumbs-up"),
   inline = TRUE
      ))  

```


### Biomass

In the Following, please check as if the  

```{r}

fluidPage(
  fluidRow(
     h4("Are cultivated plants (Terrestrial, Aquatic) strategic for the territory for nutrition, materials or energy ?"), 
     column(12,
            switchInput(inputId = "Id011",
                        label = "Terrestrial", 
                        onStatus = "success",
                        offStatus = "danger",
                        onLabel = "Yes",
                        offLabel = "No"
                        )
            ),
     column(12,
            switchInput(inputId = "Id011",
                        label = "Aquatic", 
                        onStatus = "success",
                        offStatus = "danger",
                        onLabel = "Yes",
                        offLabel = "No"
                        )
            )
    
  )

)  


```


